version: '3'

services:
  web:
    build: .
    environment:
      FLASK_APP: market.py
      FLASK_ENV: development
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0 --port 5000
